[project]
name = "diary-generator"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "jinja2>=3.1.6",
    "requests>=2.32.3",
]
[tool.ruff.lint]
extend-select = ["I"]
