name: Deploy to VPS
on:
  push:
    branches:
      - main  # 変更を適用するブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~gorou12/diary_generator
            find . -name "*.pyc" -exec rm -f {} +
            find . -name "__pycache__" -exec rm -rf {} +
            git pull origin main
      
      - name: Generate HTML
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~gorou12/diary_generator
            /home/gorou12/.local/bin/uv sync
            /home/gorou12/.local/bin/uv run generate.py
            rsync -avz --delete output/ /var/www/html/diary/
